"""add trips to db

Revision ID: 1159c7504ff7
Revises: d1e7454dbac2
Create Date: 2022-10-27 03:45:57.940794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1159c7504ff7'
down_revision = 'd1e7454dbac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_address', sa.String(length=50), nullable=False),
    sa.Column('src_number', sa.Integer(), nullable=False),
    sa.Column('dst_address', sa.String(length=50), nullable=False),
    sa.Column('dst_number', sa.Integer(), nullable=False),
    sa.Column('passenger_email', sa.String(length=50), nullable=False),
    sa.Column('driver_email', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('DriversLocation', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DriversLocation', 'state')
    op.drop_table('Trips')
    # ### end Alembic commands ###
